apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teedy-ingress
  namespace: teedy
  labels:
    app: teedy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: teedy.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teedy-service
            port:
              number: 8080
