apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teedy-data-pvc
  namespace: teedy
  labels:
    app: teedy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
